version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
